name: gpt

# Model parameters
context_size: 4
n_layer: 2
n_head: 2
d_embed: 128
d_ff: 512
dropout: 0.2
flash_attention: False
#context_size: 256
#n_layer: 6
#n_head: 6
#d_embed: 384
#d_ff: 1536
#dropout: 0.2
#flash_attention: False
