type: megabyte

# Model parameters
pad_id: 1  # "<|eot_id|>" token
patch_size: 4
patch_num: 16
global:
    n_layer: 2
    n_head: 2
    d_embed: 128
    d_ff: 512
    dropout: 0.2
local:
    n_layer: 2
    n_head: 2
    d_embed: 128
    d_ff: 512
    dropout: 0.2

model_path: models/megabyte/checkpoints/megabyte.pth