name: megabyte

# Model parameters
context_size: 256
pad_id: 1  # "<|eot_id|>" token
patch_size: 4
global:
  n_layer: 3
  n_head: 4
  d_embed: 256
  d_ff: 1024
  dropout: 0.2
local:
  n_layer: 2
  n_head: 4
  d_embed: 256
  d_ff: 1024
  dropout: 0.2
